// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJsQTruhWM-gqUw_VGqxvDdaZ6FUDzLo',
    appId: '1:291914478016:android:72e2fec39a30d3383a9825',
    messagingSenderId: '291914478016',
    projectId: 'fir-sigin-cef53',
    storageBucket: 'fir-sigin-cef53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPlKgD5L-Ca_10eIAN1-qhG-LKtHXuj-0',
    appId: '1:291914478016:ios:f9403cb62d020a083a9825',
    messagingSenderId: '291914478016',
    projectId: 'fir-sigin-cef53',
    storageBucket: 'fir-sigin-cef53.firebasestorage.app',
    androidClientId: '291914478016-vlqsl5hdcv69gcebfhetb3qvsm2mda3r.apps.googleusercontent.com',
    iosClientId: '291914478016-aqfrp9ne7s66hqv51j6dlptse4nlc6jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSignin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgYowYLZEPTSVBkAfnBBQ-PV9n7zPNtQ',
    appId: '1:291914478016:web:d05bb90f8c401c3e3a9825',
    messagingSenderId: '291914478016',
    projectId: 'fir-sigin-cef53',
    authDomain: 'fir-sigin-cef53.firebaseapp.com',
    storageBucket: 'fir-sigin-cef53.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPlKgD5L-Ca_10eIAN1-qhG-LKtHXuj-0',
    appId: '1:291914478016:ios:f9403cb62d020a083a9825',
    messagingSenderId: '291914478016',
    projectId: 'fir-sigin-cef53',
    storageBucket: 'fir-sigin-cef53.firebasestorage.app',
    androidClientId: '291914478016-vlqsl5hdcv69gcebfhetb3qvsm2mda3r.apps.googleusercontent.com',
    iosClientId: '291914478016-aqfrp9ne7s66hqv51j6dlptse4nlc6jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSignin',
  );

}